[package]
name = "mistralrs-keyed-rng"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
candle-core.workspace = true
candle-nn.workspace = true
candle-metal-kernels = { workspace = true, optional = true }
objc2-metal = { workspace = true, optional = true }
symcoe-core = { git = "https://github.com/iamorlando/KeyedRngs.git", rev = "9269c77b9bd0095688f93fa6d9e97624211c883b", default-features = false, features = ["f32", "sobol-64-dim"] }

[features]
metal = ["candle-core/metal", "candle-nn/metal", "dep:candle-metal-kernels", "dep:objc2-metal"]
